# Generated by Django 3.2.23 on 2024-02-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
