# Generated by Django 3.2.23 on 2024-02-07 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='food',
        ),
        migrations.RemoveField(
            model_name='food',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='costomer',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='food',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
