# Generated by Django 3.2.23 on 2024-02-03 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('catagory', models.CharField(max_length=50)),
                ('cost', models.FloatField()),
                ('image', models.ImageField(upload_to='restaurant/menu/images')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costomer_name', to=settings.AUTH_USER_MODEL)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_name', to='Menu.food')),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='menu',
        ),
        migrations.AddField(
            model_name='orders',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='Menu.restaurant'),
        ),
        migrations.AddField(
            model_name='food',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_name', to='Menu.restaurant'),
        ),
    ]
