# Generated by Django 3.2.23 on 2024-02-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0002_orders_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(default='Delivered', max_length=10),
        ),
    ]
