# Generated by Django 3.2.23 on 2024-02-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0003_remove_orders_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
