# Generated by Django 3.2.23 on 2024-02-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0003_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
